version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/myapp
      - /myapp/tmp
    depends_on:
      - 'db'
      - 'redis'
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
volumes:
  redis:
